alone/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('regpage.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('userpage/', include('userpage.urls',  namespace='userpage')),
    path('people/',include('friend.urls',  namespace='friends')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alone_sn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mypage/', include('mypage.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

regpage/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'regpage'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

templates/accounts/login.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        {% include 'includes/meta.html' %}

        <link rel="stylesheet" href="{% static '/css/common.css' %} ">
        <link rel="stylesheet" href="{% static '/css/regpage.css' %} ">
    </head>
        
    <body>
       
        {% include 'includes/header.html'%}

        <section class="container">
            <div class="row reg-content">
                
                <!-- User counter -->
                <div class="col-md-6">
                    <!-- Counter block -->
                    <div class="container pt-3">
                        
                        <div class="reg-info">
                        
                            <!-- Its be count down by js -->
                            <div class="reg-label">924</div>
                            <div class="reg-label">
                                <h3>People already exist in alone</h3>
                                <h4></h4>
                            </div>
                            
                        </div>
                        
                        <img src="{% static  '/image/aloooo.jpg' %}" width="100%">
                        
                    </div>
                </div>
                
                
                <!-- Form registration -->
                <div class="col-md-6">
                    <br><br><br>
                    <div class="container reg-label">
                       Registration
                    </div>
                    <div class="container reg-form">
                        <form method="post" action="">
                            {% csrf_token %}
                            <input class="reg-field reg-standard-block" type="email" id="input" name="email" required="required" placeholder="Email"/>
                            <br>
                            <input class="reg-field reg-standard-block" type="password" name="password" required="required" placeholder="Password"/>
                            <br>
                            <button class="btn btn-primary reg-btn reg-standard-block" type="submit">Login</button>
                            <br>
                            <div class="reg-already-have">
                                <a href="{% url 'regpage:register' %}" title="">Sign Up</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
    
        {% include 'includes/footer.html'%}
        
    </body>
    
    {% include 'includes/scripts.html'%}

</html>

templates/accounts/register.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        {% include 'includes/meta.html' %}

        <link rel="stylesheet" href="{% static '/css/common.css' %} ">
        <link rel="stylesheet" href="{% static '/css/regpage.css' %} ">
    </head>
        
    <body>
       
        {% include 'includes/header.html'%}
        
        <section class="container">
            <div class="row reg-content">
                
                <!-- User counter -->
                <div class="col-md-6">
                    <!-- Counter block -->
                    <div class="container pt-3">
                        
                        <div class="reg-info">
                        
                            <!-- Its be count down by js -->
                            <div class="reg-label">924</div>
                            <div class="reg-label">
                                <h3>People already exist in alone</h3>
                                <h4></h4>
                            </div>
                            
                        </div>
                        
                        <img src="{% static  '/image/aloooo.jpg' %}" width="100%">
                        
                    </div>
                </div>
                
                
                <!-- Form registration -->
                <div class="col-md-6">
                    <div class="container reg-label">
                       Registration
                    </div>
                    <div class="container reg-form">
                        <form method="post" action="">
                             {% csrf_token %}
                            <input class="reg-field reg-standard-block" type="text" required="required" name="username" placeholder="Username"/>
                            <br>
                            <input class="reg-field reg-standard-block" type="text" required="required" name="email" placeholder="Email" />
                            <br>
                            <input class="reg-field reg-standard-block" type="password" required="required" name="password1" placeholder="Password"/>
                            <br>
                            <input class="reg-field reg-standard-block" type="password" required="required" name="password2" placeholder="Repeat pass"/>
                            <br>
                            <button class="btn btn-primary reg-btn reg-standard-block" type="submit">Sign Up</button>
                            <br>
                            <div class="reg-already-have">
                                <a href="{% url 'regpage:login' %}" title="">Already have an account</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </section>
        
        {% include 'includes/footer.html'%}
        
    </body>
    
    {% include 'includes/scripts.html'%}
</html>