alone/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('regpage.urls', namespace='accounts')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('userpage/', include('userpage.urls',  namespace='userpage')),
    path('people/',include('friend.urls',  namespace='friends')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

alone_sn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('mypage/', include('mypage.urls')),
    path('admin/', admin.site.urls),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

friend/urls.py
from django.urls import path
from .views import *

app_name = "friends"

urlpatterns = [
    path('find-friends', FindFriendsListView.as_view(), name="find-friends"),
]

regpage/urls.py
from django.contrib import admin
from django.urls import path

from .views import *

app_name = 'regpage'

urlpatterns = [
    path('register', RegisterView.as_view(), name='register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
]

userpage/urls.py
from django.urls import path
from django.contrib import admin
from .views import *

app_name = 'userpage'
urlpatterns = [
#    path('admin/', admin.site.urls, name='admin_page'),
    path('', hello),
    path('edit-profile', ProfileEditView.as_view(), name="edit-profile"),
    path('<slug:username>', UserView.as_view(), name="user-page"),
]

templates/includes/footer.html
        

    <div class="end"></div>
    <footer>                   <hr>
            <div class="container">
               <div class="row">

                   <!-- Footer links -->
                   <div class="col-md-6">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link" href="#">&copy; 2020 Alone.com</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Sources</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">About</a>
                            </li>
                            <li>
                                <a class="nav-link" id=”#Top”>On top</a>
                            </li>
                        </ul>
                   </div>
                   
                   <!-- Lanfuage tooggle -->
                   <div class="col-md-6">
                        <ul class="nav justify-content-end align-middle">
                            <li class="nav-item">
                                <div class="dropdown col-md-1 language-toggle">
                                    <button class="bg-white dropdown-toggle border-0 languege-toggle-text" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-expanded="false" >
                                        En
                                    </button>
                                    <ul class="dropdown-menu border-0  " aria-labelledby="dropdownMenuButton">
                                        <li><a class="dropdown-item languege-toggle-text" href="#">Ru</a></li>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                   
                </div>  
            </div>
        </footer>

templates/includes/header.html
        <header class="container">
            <div class="row">
                <div class="col-md-11">
                    <h1 class="logo">Alone</h1>
                    <br> <!-- i am lazy its for margin to reg content -->
                </div>
            </div> 
        </header>

templates/includes/menu.html
                <!-- Menu -->
                <div class="col-md-2">
                    <button class="menu-button"><a class="menu-button-link" href="{% url 'userpage:user-page' user.username %}">Profile</a></button>
                    <button class="menu-button"><a class="menu-button-link" href="{% url 'friends:find-friends' %}">People</a></button>
                    <button class="menu-button"><a class="menu-button-link" href="">Messanges</a></button>
                    <button class="menu-button"><a class="menu-button-link" href="">Notifications</a></button>
                </div>

templates/includes/meta.html
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge"> 
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <title>Alone</title>
        <meta name="description" content="Social network for me, because im lonely">
        <meta name="keywords" content="loneliness, depression, suicide, lack of communication, outcast">
        <link rel="icon" href="favicon.ico" type="image/x-icon" />
        
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" integrity="sha384-r4NyP46KrjDleawBgD5tp8Y7UzmLA05oM1iAEQ17CSuDqnUK2+k9luXQOfXJCJ4I" crossorigin="anonymous">

templates/includes/scripts.html
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/js/bootstrap.min.js" integrity="sha384-oesi62hOLfzrys4LxRF63OJCXdXDipiYWBnvTl9Y9/TRlw5xlKIEHpNyvvDShgf/" crossorigin="anonymous">
    </script>

templates/includes/sec_header.html
        <header class="container">
            <div class="row">
                <div class="col-md-10">
                    <h1 class="logo">Alone</h1>
                    <br> <!-- i am lazy its for margin to reg content -->
                </div>
                <div class="col-md-2"><a  class="sign-out" href="{% url 'accounts:logout' %}">Sign Out</a></div>
            </div>     
        </header>